# See the KernelCI wiki page regarding the format of this file:
# https://github.com/kernelci/kernelci-doc/wiki/Build-configurations


trees:

  saurom01:
    url: "https://github.com/saul-romero-arm/linux.git"

fragments:

  debug:
    path: "kernel/configs/debug.config"

  kselftest:
    path: "kernel/configs/kselftest.config"

  tinyconfig:
    path: "kernel/configs/tiny.config"
    defconfig: 'tinyconfig'

  virtualvideo:
    path: "kernel/configs/virtualvideo.config"
    configs:
      - 'CONFIG_MEDIA_SUPPORT=y'
      - 'CONFIG_MEDIA_CAMERA_SUPPORT=y'
      - 'CONFIG_VIDEO_DEV=y'
      - 'CONFIG_VIDEO_V4L2=y'
      - 'CONFIG_V4L_TEST_DRIVERS=y'
      - 'CONFIG_VIDEO_VIVID=y'
      - 'CONFIG_VIDEO_VIVID_MAX_DEVS=64'

  x86_kvm_guest:
    path: "kernel/configs/kvm_guest.config"


build_environments:

  gcc-8:
    cc: gcc
    cc_version: 8
    arch_map: &gcc_arch_map
      i386: 'x86'
      x86_64: 'x86'
      riscv: 'riscv64'
    cross_compile: &default_cross_compile
      arc: 'arc-elf32-'
      arm: 'arm-linux-gnueabihf-'
      arm64: 'aarch64-linux-gnu-'
      mips: 'mips-linux-gnu-'
      riscv: 'riscv64-linux-gnu-'

  clang-9:
    cc: clang
    cc_version: 9
    arch_map: &clang_arch_map
      i386:
      x86_64:
      arm:
      arm64:
      mips:
      arc:
      riscv:
    cross_compile: *default_cross_compile


# Default config with full build coverage
build_configs_defaults:
  variants:
    gcc-8:
      build_environment: gcc-8

      fragments: &default_fragments
        - 'debug'
        - 'kselftest'
        - 'tinyconfig'

      architectures: &default_architectures

        arc: &arc_arch
          base_defconfig: 'haps_hs_smp_defconfig'
          extra_configs: ['allnoconfig']
          filters: &arc_default_filters
            # remove any non-ARCv2 defconfigs since we only have ARCv2 toolchain
            - blacklist:
                defconfig:
                  - 'axs101_defconfig'
                  - 'nps_defconfig'
                  - 'nsim_700_defconfig'
                  - 'nsimosci_defconfig'
                  - 'tb10x_defconfig'

        arm: &arm_arch
          base_defconfig: 'multi_v7_defconfig'
          extra_configs:
            - 'allmodconfig'
            - 'allnoconfig'
            - 'multi_v7_defconfig+CONFIG_CPU_BIG_ENDIAN=y'
            - 'multi_v7_defconfig+CONFIG_SMP=n'
            - 'multi_v7_defconfig+CONFIG_EFI=y+CONFIG_ARM_LPAE=y'

        arm64: &arm64_arch
          extra_configs:
            - 'allmodconfig'
            - 'allnoconfig'
            - 'defconfig+CONFIG_CPU_BIG_ENDIAN=y'
            - 'defconfig+CONFIG_RANDOMIZE_BASE=y'

        i386: &i386_arch
          base_defconfig: 'i386_defconfig'
          extra_configs: ['allnoconfig']

        mips: &mips_arch
          base_defconfig: '32r2el_defconfig'
          extra_configs: ['allnoconfig']
          filters: &mips_default_filters
            - blacklist: {defconfig: ['generic_defconfig']}

        riscv: &riscv_arch
          extra_configs: ['allnoconfig']

        x86_64: &x86_64_arch
          base_defconfig: 'x86_64_defconfig'
          extra_configs: ['allmodconfig', 'allnoconfig']
          fragments: [x86_kvm_guest]

  reference:
    tree: mainline
    branch: 'master'

# Minimum architecture defconfigs
arch_defconfigs: &arch_defconfigs
  arc: &arc_defconfig
    base_defconfig: 'haps_hs_smp_defconfig'
    filters:
      - regex: { defconfig: 'haps_hs_smp_defconfig' }
  arm: &arm_defconfig
    base_defconfig: 'multi_v7_defconfig'
    filters:
      - regex: { defconfig: 'multi_v7_defconfig' }
  arm64: &arm64_defconfig
    base_defconfig: 'defconfig'
    filters:
      - regex: { defconfig: 'defconfig' }
  mips: &mips_defconfig
    base_defconfig: '32r2el_defconfig'
    filters:
      - regex: { defconfig: '32r2el_defconfig' }
  riscv: &riscv_defconfig
    base_defconfig: 'defconfig'
    filters:
      - regex: { defconfig: 'defconfig' }
  x86_64: &x86_64_defconfig
    base_defconfig: 'x86_64_defconfig'
    filters:
      - regex: { defconfig: 'x86_64_defconfig' }


minimal_variants: &minimal_variants
  gcc-8:
    build_environment: gcc-8
    architectures: *arch_defconfigs


# Build fewer kernel configs with stable branches
stable_variants: &stable_variants
  gcc-8:
    build_environment: gcc-8
    fragments: ['tinyconfig']
    architectures:
      arc:
        base_defconfig: 'haps_hs_smp_defconfig'
        extra_configs: ['allnoconfig']
        filters: *arc_default_filters
      arm:
        base_defconfig: 'multi_v7_defconfig'
        extra_configs: ['allnoconfig']
      arm64:
        extra_configs: ['allnoconfig']
      i386:
        base_defconfig: 'i386_defconfig'
        extra_configs: ['allnoconfig']
      mips:
        base_defconfig: '32r2el_defconfig'
        extra_configs: ['allnoconfig']
        filters: *mips_default_filters
      riscv:
        extra_configs: ['allnoconfig']
      x86_64:
        base_defconfig: 'x86_64_defconfig'
        extra_configs: ['allnoconfig']


build_configs:

  saurom01:
    tree: saurom01
    branch: 'master'
